services:
  api:
    image: ghcr.io/aloiscrr/notes-ai-agent-api:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.notes-ai-service.loadbalancer.server.port=8000"
      - "traefik.http.routers.notes-ai-router.rule=Host(`notes-ai-agent-api.aloiscrr.dev`)"
      - "traefik.http.routers.notes-ai-router.entrypoints=websecure"
      - "traefik.http.routers.notes-ai-router.tls.certresolver=myresolver"
    secrets:
      - notes_ai_agent_database_url
      - notes_ai_agent_gemini_api_key
      - notes_ai_agent_supabase_jwt_secret
      - notes_ai_agent_openai_api_key
    deploy:
      update_config:
        order: start-first
    networks:
      - traefik-public
    

secrets:
  notes_ai_agent_database_url:
    external: true
  notes_ai_agent_gemini_api_key:
    external: true
  notes_ai_agent_supabase_jwt_secret:
    external: true
  notes_ai_agent_openai_api_key:
    external: true

networks:
  traefik-public:
    external: true