name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Run after build-and-push job completes
    needs: build-and-push
    
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4  # Updated to latest version

      - name: Deploy
        uses: kitconcept/docker-stack-deploy@v1.0.1
        with:
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          stack_file: "docker-stack.yml"
          stack_name: "notes-ai-agent-api" 